# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        arguments: -t ge_image
        tags: ge_image
    - script: |
        docker images -a
        docker run -d -it --name great_exp_trial ge_image
        docker ps -a
        docker cp great_exp_trial:/tmp/GE/great_expectations/uncommitted/data_docs/ .
        ls -lrt
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './data_docs/'
        ArtifactName: 'report'
        publishLocation: 'Container'
        StoreAsTar: true

